# Generated by Django 4.1.1 on 2022-09-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
    ]
