# Generated by Django 4.1.1 on 2022-10-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_car_name_car_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='null', upload_to='photes/%y/%m%d'),
        ),
    ]
