# Generated by Django 4.1.1 on 2022-10-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_car_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'oxen'},
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='mohamed', max_length=50),
        ),
    ]
