# Generated by Django 4.1.1 on 2022-10-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_car_options_car_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'admin'},
        ),
    ]
